### ISSUE TITLE
Molten lead is extremely overpowerred

### ISSUE THREAD

**Issue by thelegitdolt** [GL33P-0R4NG3/oreganized#100]
1. dip yourself in molten lead
2. observe that the tick for damaging is like set to 1 or something
newest version btw

**Comment by randomuser0925** [comment]
I mean, you can't place it in a block a mob is standing on

**Comment by thelegitdolt** [comment]
https://www.youtube.com/watch?v=1vHo3-_1DGg&ab_channel=DoltHHaven this is what i meant

**Comment by Xaidee** [comment]
This, will be fixed in the next release, damage should behave more like lava
