### ISSUE TITLE
Constant Crashing When Creating & Loading Worlds

### ISSUE THREAD

**Issue by TheWastag** [GL33P-0R4NG3/oreganized#15]
First instances hung on 59% and crashed, next I fully loaded and got one frame from the world before a crash, and the rest fully loaded with no glimpse at the game. 10 attempts, crash reports below:

[crash-2021-02-04_21.01.10-server.txt](https://github.com/GL33P-0R4NG3/oreganized/files/5928556/crash-2021-02-04_21.01.10-server.txt)
[crash-2021-02-04_20.47.36-server.txt](https://github.com/GL33P-0R4NG3/oreganized/files/5928547/crash-2021-02-04_20.47.36-server.txt)
[crash-2021-02-04_20.49.29-server.txt](https://github.com/GL33P-0R4NG3/oreganized/files/5928548/crash-2021-02-04_20.49.29-server.txt)
[crash-2021-02-04_20.50.08-server.txt](https://github.com/GL33P-0R4NG3/oreganized/files/5928549/crash-2021-02-04_20.50.08-server.txt)
[crash-2021-02-04_20.51.22-server.txt](https://github.com/GL33P-0R4NG3/oreganized/files/5928550/crash-2021-02-04_20.51.22-server.txt)
[crash-2021-02-04_20.55.54-server.txt](https://github.com/GL33P-0R4NG3/oreganized/files/5928551/crash-2021-02-04_20.55.54-server.txt)
[crash-2021-02-04_20.56.33-server.txt](https://github.com/GL33P-0R4NG3/oreganized/files/5928552/crash-2021-02-04_20.56.33-server.txt)
[crash-2021-02-04_20.57.33-server.txt](https://github.com/GL33P-0R4NG3/oreganized/files/5928553/crash-2021-02-04_20.57.33-server.txt)
[crash-2021-02-04_20.59.19-server.txt](https://github.com/GL33P-0R4NG3/oreganized/files/5928554/crash-2021-02-04_20.59.19-server.txt)
[crash-2021-02-04_21.00.16-server.txt](https://github.com/GL33P-0R4NG3/oreganized/files/5928555/crash-2021-02-04_21.00.16-server.txt)

**Comment by TheWastag** [comment]
Attempted to use the 35.1.5 version of Forge at the request of @GL33P-0R4NG3 , first and third crash were 100% loads followed by a crash, the second hung at 6% and I had to use task manager to crash it. Two new crash reports below (second crash was forced):

[crash-2021-02-04_21.33.58-server.txt](https://github.com/GL33P-0R4NG3/oreganized/files/5928684/crash-2021-02-04_21.33.58-server.txt)
[crash-2021-02-04_21.30.12-server.txt](https://github.com/GL33P-0R4NG3/oreganized/files/5928685/crash-2021-02-04_21.30.12-server.txt)

**Comment by GL33P-0R4NG3** [comment]
SOLVED
