### ISSUE TITLE
Iron trapdoor and iron plates recipe conflict, lead has no forge tag for lead. [oreganized-1.16.4-0.4.4-beta]

### ISSUE THREAD

**Issue by ribs498** [GL33P-0R4NG3/oreganized#25]

**Comment by GL33P-0R4NG3** [comment]
What do you mean by "Iron trapdoor and iron plates recipe conflict" can you tell me more info or show me picture with the problem if possible?

**Comment by GL33P-0R4NG3** [comment]
Im gonna close this because no further information was provided
