### ISSUE TITLE
Crash when trying to start dedicated server

### ISSUE THREAD

**Issue by Prolixitas** [GL33P-0R4NG3/oreganized#43]
Server is running forge 1.16.4-35.1.37 with mc version 1.16.4. When trying to start the server, once it begins trying to load oreganized it crashes with the following crash log. https://pastebin.com/KuKXSWmU

Trying to run the server without oreganized allows it start properly, and as far as I can tell it's not a mod conflict.

**Comment by GL33P-0R4NG3** [comment]
Just to mention you are using the the alpha version of our mod which could have some bugs so please wait until next beta (releasing soon) and if it still occurs send it here again and i'll have a look for now I close this. Thanks for understanding!
