### ISSUE TITLE
(Suggestion) Silver retexture

### ISSUE THREAD

**Issue by PercyJames** [GL33P-0R4NG3/oreganized#53]
so, a while ago there was this 1.12.2 mod that added silver items based on the texture on ravager armor and pillager belts.

I think this mod should take a similar approach to silver. sure, there's no texture of it being blue but you could just use the color slider to do that.

![Ravager_JE1](https://user-images.githubusercontent.com/65469481/126704584-a11fc182-b8a3-4b28-8a8c-90ca731fd86e.png)

notice the armor on the ravager

![Pillager_JE2](https://user-images.githubusercontent.com/65469481/126704681-d7cdfeb3-cfd2-4295-902b-d8a96f81e4cb.png)

notice the belt buckle and shoulder pads.

**Comment by GL33P-0R4NG3** [comment]
Since the uncorruptible nature of silver, we concluded that this must be iron because it wouldn't make much sense to have something incorruptible on corrupt creatures.
Sorry
