### ISSUE TITLE
Crash on dedicated server

### ISSUE THREAD

**Issue by Sixdd6** [GL33P-0R4NG3/oreganized#56]
Client classes loading on server.

[crash-2021-08-13_18.17.15-fml.txt](https://github.com/GL33P-0R4NG3/oreganized/files/6985543/crash-2021-08-13_18.17.15-fml.txt)

**Comment by Sixdd6** [comment]
#43

**Comment by Sixdd6** [comment]
Is this ever gonna get seen? Don't mean to be impatient but I couldn't help but notice the bug still exists and crashes on servers.

**Comment by zKryle** [comment]
This mod is currently in development and really close to 1.0, this bug has already been addressed and fixed in the 1.18.1. 1.16.5 is discontinued. Join the discord for more info!
